name: Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: upstream-378723
  GAR_LOCATION: us-west1
  SERVICE: upstream-cloud-run
  REGION: us-west1

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Google Auth using credentials JSON
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Check Cloud Run Service Status
      - name: Check Cloud Run Service Status
        run: |
          gcloud run services describe ${{ env.SERVICE }} --region=${{ env.REGION }} --platform=managed

